[changelog]
header = """
# Changelog

All notable changes to this project are documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
"""

body = """
{% macro print_commit(commit) -%}
    - {% if commit.scope %}*({{ commit.scope }})* {% endif %}\
      {% if commit.breaking %}[**breaking**] {% endif %}\
      {{ commit.message | upper_first }} \
      ([{{ commit.id | truncate(length=7, end="") }}]({{ self::remote_url() }}/commit/{{ commit.id }}))\
{% endmacro -%}

{% macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}

{% if version -%}
    ## 🚀 [{{ version | trim_start_matches(pat="v") }}]({{ self::remote_url() }}/compare/{{ previous.version }}..{{ version }}) ({{ timestamp | date(format="%Y-%m-%d") }})
{% else -%}
    ## 🚧 Unreleased
{% endif %}

{% for group, commits in commits | filter(attribute="merge_commit", value=false) | group_by(attribute="group") %}
    ### {{ group | striptags | trim | upper_first }}
    {% for commit in commits %}
        {{ self::print_commit(commit=commit) }}
    {%- endfor %}
{% endfor %}

{%- if github.contributors | filter(attribute="is_first_time", value=true) | length != 0 %}
  ### ❤️ New Contributors
  {% for contributor in github.contributors | filter(attribute="is_first_time", value=true) %}
    - @{{ contributor.username }} made their first contribution in [#{{ contributor.pr_number }}]({{ self::remote_url() }}/pull/{{ contributor.pr_number }})
  {%- endfor %}
{%- endif %}
"""

footer = ""
trim = true

postprocessors = [
  { pattern = '<REPO>', replace = "https://github.com/noirbizarre/gh-settings" },
]

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
protect_breaking_commits = true
filter_commits = false
tag_pattern = "[0-9]*"
topo_order = false
sort_commits = "newest"

commit_preprocessors = [
  # Fix typos in commit messages before they are immortalised in the changelog.
  { pattern = '.*', replace_command = 'typos --write-changes -' },
]

commit_parsers = [
  { message = "^feat", group = "<!-- 0 -->💫 Features" },
  { message = "^fix", group = "<!-- 1 -->🐛 Bug Fixes" },
  { message = "^perf", group = "<!-- 2 -->⚡ Performance" },
  { message = "^refactor", group = "<!-- 3 -->🔨 Refactor" },
  { message = "^docs", group = "<!-- 4 -->📚 Documentation" },
  { message = "^test", group = "<!-- 5 -->🧪 Tests" },
  { message = "^style", group = "<!-- 6 -->🎨 Style" },
  { message = "^build", group = "<!-- 7 -->🏗️ Build" },
  { message = "^ci", group = "<!-- 8 -->🔧 CI" },
  { message = "^revert", group = "<!-- 9 -->⏪ Reverts" },
  { message = "^chore\\(release\\)", skip = true },
  { message = "^chore\\(deps\\)", skip = true },
  { message = "^chore", group = "<!-- 10 -->🧹 Chores" },
]

[bump]
features_always_bump_minor = true
breaking_always_bump_major = true
