//! `gh settings export`.
//!
//! Generates a configuration file from a repository's current state, so adopting
//! the tool on an existing repository is a single command.
//!
//! # Comments are not preserved
//!
//! No Rust YAML library round-trips comments, so export always writes a fresh
//! document. Overwriting an existing file therefore requires `--force`.

use miette::Result;

use crate::cli::context::Context;
use crate::cli::exit;

/// Arguments for `export`.
#[derive(Debug, Default, clap::Args)]
pub struct Args {
    /// Write to standard output instead of a file.
    #[arg(long)]
    pub stdout: bool,

    /// Overwrite an existing configuration file.
    #[arg(short, long)]
    pub force: bool,

    /// Path to write to. Defaults to `.github/settings.yml`.
    #[arg(short, long, value_name = "PATH")]
    pub out: Option<std::path::PathBuf>,
}

/// Run the command.
pub async fn run(args: &Args, ctx: &Context) -> Result<i32> {
    let settings = ctx
        .engine
        .export(ctx.client(), &ctx.target, &ctx.args.only)
        .await?;

    let document = serde_yaml_ng::to_string(&settings)
        .map_err(|error| miette::miette!("could not render the configuration: {error}"))?;

    let header = format!(
        "# yaml-language-server: $schema={}\n\
         # Generated by `gh settings export` from {}.\n\
         # Review before committing: exported files describe current state, not intent.\n",
        crate::schema::schema_id(),
        ctx.target
    );
    let contents = format!("{header}{document}");

    if args.stdout {
        print!("{contents}");
        return Ok(exit::SUCCESS);
    }

    let path = args
        .out
        .clone()
        .unwrap_or_else(|| std::path::PathBuf::from(crate::config::discover::CANDIDATES[0]));

    if path.exists() && !args.force {
        return Err(miette::miette!(
            help = "pass `--force` to overwrite, or `--stdout` to inspect it first",
            "{} already exists, and export cannot preserve its comments",
            path.display()
        ));
    }

    if let Some(parent) = path.parent()
        && !parent.as_os_str().is_empty()
    {
        std::fs::create_dir_all(parent)
            .map_err(|error| miette::miette!("could not create {}: {error}", parent.display()))?;
    }

    std::fs::write(&path, &contents)
        .map_err(|error| miette::miette!("could not write {}: {error}", path.display()))?;

    eprintln!("Wrote {}", path.display());
    eprintln!("Run `gh settings plan` to confirm it reports no changes.");

    Ok(exit::SUCCESS)
}
