//! JSON Schema generation.
//!
//! The schema is the public contract (ADR-007). It is generated from the Rust
//! types rather than hand-written, so the two can never disagree, and it is
//! committed to the repository so that CI fails on any accidental change.
//!
//! Users opt into editor support with:
//!
//! ```yaml
//! # yaml-language-server: $schema=https://gh-settings.dev/schema/v1/settings.json
//! ```

use serde_json::{Map, Value};

use crate::config::Settings;
use crate::config::settings::CURRENT_VERSION;

/// Base URL the schema is published under.
pub const SCHEMA_BASE_URL: &str = "https://gh-settings.dev/schema";

/// The canonical `$id` of the current schema.
pub fn schema_id() -> String {
    format!("{SCHEMA_BASE_URL}/v{CURRENT_VERSION}/settings.json")
}

/// Generate the JSON Schema for the configuration file.
pub fn generate() -> Value {
    let mut schema = serde_json::to_value(schemars::schema_for!(Settings))
        .unwrap_or_else(|error| panic!("the schema should always serialise: {error}"));

    if let Some(object) = schema.as_object_mut() {
        // `$id` is what lets editors and `$ref`s resolve the schema, and it is
        // versioned by major so a v2 can be published alongside v1.
        object.insert("$id".into(), Value::String(schema_id()));
        object.insert(
            "$comment".into(),
            Value::String(format!(
                "Generated by gh-settings {}. Do not edit by hand; run `gh settings schema`.",
                env!("CARGO_PKG_VERSION")
            )),
        );
    }

    schema
}

/// Render the schema as the exact bytes committed to `schema/v1/settings.json`.
///
/// Pretty-printed with a trailing newline so the committed file is diff-friendly
/// and passes the end-of-file hook.
pub fn render() -> String {
    format!(
        "{}\n",
        serde_json::to_string_pretty(&generate())
            .unwrap_or_else(|error| panic!("the schema should always render: {error}"))
    )
}

/// Every documented property of the configuration root.
///
/// Used by the documentation generator to emit the configuration reference from
/// the schema rather than from hand-maintained prose.
pub fn root_properties() -> Vec<(String, Value)> {
    let schema = generate();
    let Some(properties) = schema
        .get("properties")
        .and_then(Value::as_object)
        .cloned()
        .or_else(|| Some(Map::new()))
    else {
        return Vec::new();
    };

    let mut entries: Vec<(String, Value)> = properties.into_iter().collect();
    entries.sort_by(|(a, _), (b, _)| a.cmp(b));
    entries
}

#[cfg(test)]
mod tests {
    use super::*;
    use pretty_assertions::assert_eq;

    #[test]
    fn the_schema_declares_a_versioned_id() {
        let schema = generate();
        assert_eq!(
            schema["$id"],
            Value::String("https://gh-settings.dev/schema/v1/settings.json".into())
        );
    }

    #[test]
    fn the_schema_documents_every_section() {
        // A section that is not in the schema is invisible to editors and to the
        // generated documentation.
        let schema = generate();
        let properties = schema["properties"].as_object().expect("properties");

        for section in [
            "version",
            "repository",
            "topics",
            "labels",
            "autolinks",
            "rulesets",
        ] {
            assert!(properties.contains_key(section), "{section} is missing");
        }
    }

    #[test]
    fn the_schema_carries_a_title_and_description() {
        let schema = generate();
        assert!(schema.get("title").is_some());
        assert!(schema.get("description").is_some());
    }

    #[test]
    fn unknown_sections_are_rejected() {
        // `deny_unknown_fields` must survive into the schema, or editors would
        // accept typos that the CLI then refuses.
        let schema = generate();
        assert_eq!(
            schema.get("additionalProperties"),
            Some(&Value::Bool(false))
        );
    }

    #[test]
    fn the_rendered_form_ends_with_a_newline() {
        assert!(render().ends_with("}\n"));
    }

    #[test]
    fn generation_is_deterministic() {
        // The committed schema is diffed in CI, so any instability here would
        // produce spurious failures.
        assert_eq!(render(), render());
    }

    #[test]
    fn root_properties_are_sorted() {
        let names: Vec<String> = root_properties()
            .into_iter()
            .map(|(name, _)| name)
            .collect();
        let mut sorted = names.clone();
        sorted.sort();
        assert_eq!(names, sorted);
    }
}
